import {
  GET_ALERTS_ALL,
  GET_COMPONENTS_ALL,
  GET_COMPONENTS_BY_PAGE,
  GET_LINKS_ALL,
  GET_LINKS_BY_PAGE,
  GET_FORMS_ALL,
  GET_FORMS_BY_PAGE,
  GET_PAGES_ALL,
  GET_POSTS_ALL,
  GET_SITE_ALL,
  GET_SOCIALS_ALL,
} from "./queries";

export {
  GET_ALERTS_ALL,
  GET_COMPONENTS_ALL,
  GET_COMPONENTS_BY_PAGE,
  GET_LINKS_ALL,
  GET_LINKS_BY_PAGE,
  GET_FORMS_ALL,
  GET_FORMS_BY_PAGE,
  GET_PAGES_ALL,
  GET_POSTS_ALL,
  GET_SITE_ALL,
  GET_SOCIALS_ALL,
};
